<a href="https://colab.research.google.com/github/Aniket1313/Python_ML_Practice/blob/master/Ch07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Chapter 7 :Prepare Data for Machine Learning 

Recipes:
1. Rescale data
2. Standardize data 
3. Normalize data
4. Binarize Data

In [2]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

In [5]:
filename = 'pima-indians-diabetes.csv'
names = ['preg','plans','skin','test','mass','pedi','age','class']
df = pd.read_csv(filename,names=names)

In [6]:
df.head(10)

preg  plans  skin  test  mass   pedi  age  class
6    148     72    35     0  33.6  0.627   50      1
1     85     66    29     0  26.6  0.351   31      0
8    183     64     0     0  23.3  0.672   32      1
1     89     66    23    94  28.1  0.167   21      0
0    137     40    35   168  43.1  2.288   33      1
5    116     74     0     0  25.6  0.201   30      0
3     78     50    32    88  31.0  0.248   26      1
10   115      0     0     0  35.3  0.134   29      0
2    197     70    45   543  30.5  0.158   53      1
8    125     96     0     0   0.0  0.232   54      1

In [7]:
from numpy import set_printoptions
from sklearn.preprocessing import MinMaxScaler

In [11]:
array = df.values
array.shape

(768, 8)

In [12]:
array.size

6144

In [31]:
X = array[:, 0:8]
Y = array[:, 7]

In [32]:
print(X.shape ,Y.shape)

(768, 8) (768,)


In [29]:
from numpy import set_printoptions
scaler = MinMaxScaler(feature_range =(0, 1))
rescaledX =scaler.fit_transform(X)
#summarize transformed data
set_printoptions(precision=3)

In [20]:
rescaledX[:10]

array([[0.744, 0.59 , 0.354, 0.   , 0.501, 0.234, 0.483, 1.   ],
       [0.427, 0.541, 0.293, 0.   , 0.396, 0.117, 0.167, 0.   ],
       [0.92 , 0.525, 0.   , 0.   , 0.347, 0.254, 0.183, 1.   ],
       [0.447, 0.541, 0.232, 0.111, 0.419, 0.038, 0.   , 0.   ],
       [0.688, 0.328, 0.354, 0.199, 0.642, 0.944, 0.2  , 1.   ],
       [0.583, 0.607, 0.   , 0.   , 0.382, 0.053, 0.15 , 0.   ],
       [0.392, 0.41 , 0.323, 0.104, 0.462, 0.073, 0.083, 1.   ],
       [0.578, 0.   , 0.   , 0.   , 0.526, 0.024, 0.133, 0.   ],
       [0.99 , 0.574, 0.455, 0.642, 0.455, 0.034, 0.533, 1.   ],
       [0.628, 0.787, 0.   , 0.   , 0.   , 0.066, 0.55 , 1.   ]])

In [21]:
rescaledX.shape

(768, 8)

In [22]:
print(rescaledX[0:5,:])

[[0.744 0.59  0.354 0.    0.501 0.234 0.483 1.   ]
 [0.427 0.541 0.293 0.    0.396 0.117 0.167 0.   ]
 [0.92  0.525 0.    0.    0.347 0.254 0.183 1.   ]
 [0.447 0.541 0.232 0.111 0.419 0.038 0.    0.   ]
 [0.688 0.328 0.354 0.199 0.642 0.944 0.2   1.   ]]


#7.6 Binarize Data (Make Binary)

Useful when have probablities.New features that indicate meaningful.

In [34]:
from sklearn.preprocessing import Binarizer 

In [35]:
binarizer = Binarizer(threshold = 0.0).fit(X)
binaryX = binarizer.transform(X)

#summarize transformed data
set_printoptions(precision=3)
print(binaryX[0:5,:])

[[1. 1. 1. 0. 1. 1. 1. 1.]
 [1. 1. 1. 0. 1. 1. 1. 0.]
 [1. 1. 0. 0. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
